import express from "express";
import path from "path";
import { createServer as createViteServer } from "vite";
import { GoogleGenAI } from "@google/genai";
import dotenv from "dotenv";

dotenv.config();

const SYSTEM_PROMPT = `You are EngiSolve, an expert mechanical engineering tutor. A student will give you a problem statement and the subject it belongs to (Thermodynamics, Fluid Mechanics, Heat Transfer, Machine Design, Manufacturing Processes, or Engineering Math).

Always answer using EXACTLY this structure, with these headings, in this order:

**Given / Known Data**
- List every value provided in the problem with units.

**Assumptions**
- State any standard engineering assumptions needed to solve it (e.g., ideal gas, steady state, negligible friction) — only if relevant. If none are needed, say "No additional assumptions required."

**Governing Equation(s)**
- Name and write the relevant equation(s) in standard engineering notation.

**Solution Steps**
- Solve step by step, showing substitution of values and intermediate results. Keep units attached at every step.

**Units Check**
- Briefly confirm the final answer's units are dimensionally correct.

**Final Answer**
- State the final numeric result clearly, bolded, with correct units and appropriate significant figures.

Rules:
- If the problem is ambiguous or missing data, ask ONE clarifying question instead of guessing, under a "Clarification Needed" heading.
- If it's a conceptual (non-numeric) question, skip Units Check and answer with Given/Context, Explanation, and Key Takeaway instead.
- Be concise but complete — no filler, no repeating the question back verbatim.
- Never fabricate formulas; if unsure, say so explicitly rather than guessing.`;

async function startServer() {
  const app = express();
  const PORT = 3000;

  app.use(express.json({ limit: "1mb" }));

  // Health check endpoint
  app.get("/api/health", (_req, res) => {
    res.json({
      status: "ok",
      app: "EngiSolve",
      timestamp: new Date().toISOString(),
      hasApiKey: !!process.env.GEMINI_API_KEY,
    });
  });

  // AI Problem Solving Endpoint
  app.post("/api/solve", async (req, res) => {
    try {
      const { subject, problem, model: customModel } = req.body;

      if (!subject || typeof subject !== "string") {
        return res.status(400).json({ error: "Subject is required." });
      }

      if (!problem || typeof problem !== "string" || !problem.trim()) {
        return res.status(400).json({ error: "Problem statement is required." });
      }

      const apiKey = process.env.GEMINI_API_KEY;
      if (!apiKey) {
        return res.status(500).json({
          error: "GEMINI_API_KEY environment variable is missing on server.",
        });
      }

      const ai = new GoogleGenAI({
        apiKey,
        httpOptions: {
          headers: {
            "User-Agent": "aistudio-build",
          },
        },
      });

      // Default to gemini-3.6-flash for fast, structured STEM outputs
      const modelToUse = customModel || "gemini-3.6-flash";

      const userMessage = `Subject: ${subject.trim()}\nProblem: ${problem.trim()}`;

      const response = await ai.models.generateContent({
        model: modelToUse,
        contents: userMessage,
        config: {
          systemInstruction: SYSTEM_PROMPT,
          temperature: 0.2, // Low temperature for deterministic engineering math accuracy
        },
      });

      const solutionText = response.text || "No response generated by model.";

      return res.json({
        subject,
        problem,
        solution: solutionText,
        modelUsed: modelToUse,
        timestamp: new Date().toISOString(),
      });
    } catch (err: any) {
      console.error("Error in /api/solve:", err);
      return res.status(500).json({
        error: err.message || "An unexpected error occurred while processing the engineering problem.",
      });
    }
  });

  // Vite middleware for development vs static production serving
  if (process.env.NODE_ENV !== "production") {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), "dist");
    app.use(express.static(distPath));
    app.get("*", (_req, res) => {
      res.sendFile(path.join(distPath, "index.html"));
    });
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`EngiSolve server running on http://localhost:${PORT}`);
  });
}

startServer().catch((err) => {
  console.error("Failed to start server:", err);
});
