import { GoogleGenAI } from "@google/genai";

const SYSTEM_PROMPT = `You are EngiSolve, an expert mechanical engineering tutor. A student will give you a problem statement and the subject it belongs to (Thermodynamics, Fluid Mechanics, Heat Transfer, Machine Design, Manufacturing Processes, or Engineering Math).

Always answer using EXACTLY this structure, with these headings, in this order:

**Given / Known Data**
- List every value provided in the problem with units.

**Assumptions**
- State any standard engineering assumptions needed to solve it (e.g., ideal gas, steady state, negligible friction) — only if relevant. If none are needed, say "No additional assumptions required."

**Governing Equation(s)**
- Name and write the relevant equation(s) in standard engineering notation.

**Solution Steps**
- Solve step by step, showing substitution of values and intermediate results. Keep units attached at every step.

**Units Check**
- Briefly confirm the final answer's units are dimensionally correct.

**Final Answer**
- State the final numeric result clearly, bolded, with correct units and appropriate significant figures.

Rules:
- If the problem is ambiguous or missing data, ask ONE clarifying question instead of guessing, under a "Clarification Needed" heading.
- If it's a conceptual (non-numeric) question, skip Units Check and answer with Given/Context, Explanation, and Key Takeaway instead.
- Be concise but complete — no filler, no repeating the question back verbatim.
- Never fabricate formulas; if unsure, say so explicitly rather than guessing.`;

export default async function handler(req: any, res: any) {
  if (req.method !== "POST") {
    return res.status(405).json({ error: "Method not allowed" });
  }

  try {
    const { subject, problem, model: customModel } = req.body || {};

    if (!subject || typeof subject !== "string") {
      return res.status(400).json({ error: "Subject is required." });
    }

    if (!problem || typeof problem !== "string" || !problem.trim()) {
      return res.status(400).json({ error: "Problem statement is required." });
    }

    const apiKey = process.env.GEMINI_API_KEY;
    if (!apiKey) {
      return res.status(500).json({
        error: "GEMINI_API_KEY environment variable is missing on server.",
      });
    }

    const ai = new GoogleGenAI({
      apiKey,
    });

    const modelToUse = customModel || "gemini-3.6-flash";
    const userMessage = `Subject: ${subject.trim()}\nProblem: ${problem.trim()}`;

    const response = await ai.models.generateContent({
      model: modelToUse,
      contents: userMessage,
      config: {
        systemInstruction: SYSTEM_PROMPT,
        temperature: 0.2,
      },
    });

    const solutionText = response.text || "No response generated by model.";

    return res.status(200).json({
      subject,
      problem,
      solution: solutionText,
      modelUsed: modelToUse,
      timestamp: new Date().toISOString(),
    });
  } catch (err: any) {
    console.error("Error in /api/solve handler:", err);
    return res.status(500).json({
      error: err.message || "An unexpected error occurred while processing the engineering problem.",
    });
  }
}
